### ISSUE TITLE
Add a section into doc about projects using OnlineTechnicalIndicators.jl

### ISSUE THREAD

**Issue by femtotrader** [femtotrader/OnlineTechnicalIndicators.jl#17]
Hello,

Maybe we should add a section into documentation about projects that are using OnlineTechnicalIndicators.jl

I currently see [TechnicalIndicatorCharts.jl](https://github.com/g-gundam/TechnicalIndicatorCharts.jl) from @g-gundam
but some others may be existing

An other section about related project ie project sharing similar concepts like [OnlinePortfolioAnalytics.jl](https://github.com/femtotrader/OnlinePortfolioAnalytics.jl) should probably be also written.

Best regards

**Comment by g-gundam** [comment]
I think that's a good idea.  I think I'm going to make an early release of TechnicalIndicatorCharts.jl even though there's a lot of work left to be done on it, because I'd like to get a little more exposure for these libraries and maybe attract some helpful people.
